# Hex number of the color that should be used in embeds etc. 
color = 0x63A6CB
# Default language of the bot (https://discord.com/developers/docs/reference#locales)
defaultLocale = "en-US"

##
## Modules section 
##
[modules]

[modules.activity]
# How often to save to database
savePeriod = "5m"
# How precisely is activity tracked (e.g. "1m" = check every minute if the user is active)
activityPeriod = "1m"
# Minimum number of members in a voice chat to consider as active
minVoiceChatMembers = 2
# Whether to consider muted memebers in voice chat as active
allowMuted = true
# Whether to consider deaf memebers in voice chat as active
allowDeaf = false
# Whether to consider deafened people towards the minVoiceChatMembers limit
allowOthersDeaf = true

# AI module
[modules.ai]
baseUrl = "http://localhost:5000"
maxHistory = 64
replyDelay = "10s"
defaultContext = "A group chat."

[modules.ai.parameters]
max_new_tokens = 200
seed = -1
stop_at_newline = false
# NovelAI-Pleasing Results preset
do_sample = true
temperature = 0.44
top_p = 1
top_k = 0
typical_p = 1
repetition_penalty = 1.15
encoder_repetition_penalty = 1
no_repeat_ngram_size = 0
min_length = 0
num_beams = 1
length_penalty = 1
penalty_alpha = 0
early_stopping = false
truncation_length = 1536
add_bos_token = true
ban_eos_token = false
skip_special_tokens = true

# Birthdays module
[modules.birthdays]
images = [
  # Sourced from https://twitter.com/IKEAsame/status/1215976200813699072
  "https://pbs.twimg.com/media/EOAD3dAUcAACa5C?format=jpg",
  "https://pbs.twimg.com/media/EOAD38DVUAADiIm?format=jpg",
  "https://pbs.twimg.com/media/EOAD4bMVUAEhmLm?format=jpg",
  "https://pbs.twimg.com/media/EOAD5SNUEAA9yww?format=jpg",
  "https://pbs.twimg.com/media/EOAD51hUcAIyhpd?format=jpg",
]

# Player module
[modules.player]
maxQueueLength = 256
timeout = "15m"

songCache = { ttl = "48h", size = 2048 }

# Moderation module
[modules.moderation]
warnPenalties = [
  { count = 2, perTime = "1h", duration = "30m" },
  { count = 3, perTime = "12h", duration = "2h" },
  { count = 6, perTime = "24h", duration = "7d" },
]

[modules.moderation.logging]
logNickname = true
logDeleted = true
logEdited = false
editThreshold = 0.25

## !!!
## Advanced section 
## !!!
[system]

#journalIdentifier =
