# Hex number of the color that should be used in embeds etc. 
color = 0x63A6CB
# Default language of the bot
defaultLocale = "en"

##
## Modules section 
##
[modules]

# Activities module
[modules.activities]

youtube = "880218394199220334"

# Birthdays module
[modules.birthdays]

images = [
  # Sourced from https://twitter.com/IKEAsame/status/1215976200813699072
  "https://pbs.twimg.com/media/EOAD3dAUcAACa5C?format=jpg",
  "https://pbs.twimg.com/media/EOAD38DVUAADiIm?format=jpg",
  "https://pbs.twimg.com/media/EOAD4bMVUAEhmLm?format=jpg",
  "https://pbs.twimg.com/media/EOAD5SNUEAA9yww?format=jpg",
  "https://pbs.twimg.com/media/EOAD51hUcAIyhpd?format=jpg"
]

# Player module
[modules.player]

maxQueueLength = 256
timeout = "15m"

songCache = { ttl = "48h", size = 2048 }

# Moderation module
[modules.moderation]

warnPenalties = [
  { count = 2, perTime = "1h", duration = "30m" },
  { count = 3, perTime = "12h", duration = "2h" },
  { count = 6, perTime = "24h", duration = "7d" },
]

## !!!
## Advanced section 
## !!!
[system]

#journalIdentifier = 
